### PR TITLE
Updates and fixes while integrating w/ ADAL

### LINKED ISSUE #42: ADAL Integration Fixes
- A number of fixes applied while integrating common w/ ADAL

### PR DESCRIPTION
**Pull request by shoatman**
Closes #42

### CODE REVIEW

File: common/src/main/java/com/microsoft/identity/common/internal/providers/azureactivedirectory/AzureActiveDirectoryOAuth2Strategy.java [hunk 1]
```diff
@@ -1,20 +1,38 @@
...
+
 
 /**
  * The Azure Active Directory oAuth2 Strategy
  */
 public class AzureActiveDirectoryOAuth2Strategy extends OAuth2Strategy {
 
+    private AzureActiveDirectoryOAuth2Configuration mConfig = null;
+
+    public AzureActiveDirectoryOAuth2Strategy(OAuth2Configuration config) {
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/azureactivedirectory/AzureActiveDirectoryOAuth2Strategy.java]: At a glance, we should be able to get away with specifying the constructor parameter on `AzureActiveDirectoryOAuth2Strategy ` as `AzureActiveDirectoryOAuth2Configuration` so long as it extends `OAuth2Configuration` -- would still let you call `super()` and avoids the `instanceof` check
