### PR TITLE
Fix for #945, resolves NPE when sub_error is null

### LINKED ISSUE #945: NPE when sub_error is null in AAD response
[ADO: Tracking (corpnet reqd)](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1063189)

----
Affects: MSAL 1.5.3

Root cause:
Querying `sub_error` with `.equals()` prior to asserting it is not `null` -- `sub_error` is _optional_.

```java
Attempt: 0, Failed to refresh tokens No authentication result was received. An exception occurred: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference com.microsoft.identity.client.exception.MsalClientException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
    at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1673)
    at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1664)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:209)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7110)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: com.microsoft.identity.common.exception.ClientException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.microsoft.identity.common.internal.controllers.ExceptionAdapter.baseExceptionFromException(ExceptionAdapter.java:254)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:171)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$200(CommandDispatcher.java:65)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:126)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.microsoft.identity.common.internal.controllers.BaseController.renewAccessToken(BaseController.java:311)
    at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireTokenSilent(LocalMSALController.java:309)
    at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:75)
    at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:41)
    at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:166)
```

### PR DESCRIPTION
**Pull request by iambmelt**
Closes #945 

## [View this PR without whitespace changes](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/946/files?w=1)

### CODE REVIEW

File: common/src/main/java/com/microsoft/identity/common/internal/controllers/BaseController.java [hunk 1]
```diff
@@ -308,13 +308,17 @@ protected void renewAccessToken(@NonNull final SilentTokenCommandParameters para
                 final String subErrorCode = tokenResult.getErrorResponse().getSubError();
                 Logger.info(TAG, "Error: " + errorCode + " Suberror: " + subErrorCode);
 
-                if (errorCode.equals(INVALID_GRANT) && subErrorCode.equals(BAD_TOKEN)) {
+                if (null != errorCode && errorCode.equals(INVALID_GRANT)
+                        && null != subErrorCode && subErrorCode.equals(BAD_TOKEN)) {
```
Comment (AdamBJohnsonx) [inline common/src/main/java/com/microsoft/identity/common/internal/controllers/BaseController.java:312]: INVALID_GRANT.equals(errorCode) && BAD_TOKEN.equals(subErrorCode) ?

Comment (iambmelt) [reply common/src/main/java/com/microsoft/identity/common/internal/controllers/BaseController.java:312]: Yeah let's flip it
