### PR TITLE
Closes #607, #604

### LINKED ISSUE #607: FoCI cache tests need updating
Tests were broken by fixes submitted in #599 and #594 - this item is to update the tests

### PR DESCRIPTION
**Pull request by iambmelt**
Re-introduces AT lookups into family queries- API has been updated to include a `target` parameter.

### CODE REVIEW

File: common/src/main/java/com/microsoft/identity/common/internal/cache/MicrosoftFamilyOAuth2TokenCache.java [hunk 1]
```diff
@@ -125,9 +130,27 @@ public ICacheRecord loadByFamilyId(@Nullable final String clientId,
             }
         }
 
+        if (null != target) {
+            for (final Credential credential : getAccountCredentialCache().getCredentials()) {
+                if (credential instanceof AccessTokenRecord) {
+                    final AccessTokenRecord atRecord = (AccessTokenRecord) credential;
+
+                    if (null != clientId && clientId.equals(atRecord.getClientId())
```
Comment (shahzaibj) [inline common/src/main/java/com/microsoft/identity/common/internal/cache/MicrosoftFamilyOAuth2TokenCache.java]: This entire boolean condition could be refactored into a separate boolean method

Comment (iambmelt) [reply common/src/main/java/com/microsoft/identity/common/internal/cache/MicrosoftFamilyOAuth2TokenCache.java]: I'll elect not to take this change based on a few points:

- Increases method count
- You still need to read the method to determine how the check works
- Little potential for reuse
