### PR TITLE
Fix issue #709, #718

### LINKED ISSUE #709: Environment not set correctly on Credentials (to be cached)
When creating cache records (AccessTokenRecord, RefreshTokenRecord, IdTokenRecord) to save to the cache, we are not setting the environment correctly on them. As a result, we get a cache miss when making a silent request.

### LINKED ISSUE #718: Need to match authority with account for silent request
Need to match authority with account for silent request before making refresh token request. If the account is a sovereign cloud, however, the authority passed is worldwide, we should not make the request to the server and just throw an exception if account and authority don't match.

We are currently making the request to the server and receive an error response from the server that says Invalid National Cloud is specified.

### PR DESCRIPTION
**Pull request by shahzaibj**
Fixes #709 
Fixes #718 

In this PR, I've added the following fix for issue #709 :
Instead of setting the environment from the authorization request, we would now set it from the token endpoint as that will be the correct one.

Also set the token endpoint by querying openid provider config metadata

To fix issue #718, we will know throw an exception if the cloud associated to the account passed by the user and the authority passed by the user as part of silent parameters do not match. We achieve this by doing a reverse lookup from the `mEnvironment` field on the account object and get the cloud associated to that preferredCacheHostName. From the cloud, then we get the `preferredNetworkHostName` and we see if it matches with the authority passed by the user. If not, we throw an exception.

### CODE REVIEW

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java [hunk 1]
```diff
@@ -212,23 +233,7 @@ public MicrosoftStsAccount createAccount(
...
-            Logger.verbose(
-                    TAG + methodName,
-                    "Creating account from TokenResponse failed due to malformed URL (mTokenEndpoint)..."
-            );
-        }
-
-        if (authority != null) {
-            account.setEnvironment(getIssuerCacheIdentifierFromAuthority(authority));
-        }
+        account.setEnvironment(getIssuerCacheIdentifierFromTokenEndpoint());
```
Comment (rpdome) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: should we use this as a single source of truth?

Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: I've fixed this in MSAL, we will now get cache identifier from token endpoint in MSALOAuth2TokenCache. However, I am not going to remove the `getIssuerCacheIdentifier(AuthorizationRequest)` method as that is an abstract method and is being overridden by a few different classes.

File: common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/OpenIdProviderConfigurationClient.java [hunk 2]
```diff
@@ -54,16 +56,30 @@
     private static final ExecutorService sBackgroundExecutor = Executors.newCachedThreadPool();
     private static final Map<URL, OpenIdProviderConfiguration> sConfigCache = new HashMap<>();
 
+    private static final String NA = "";
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/OpenIdProviderConfigurationClient.java]: I don't see a constant being necessary for one usage -- I'm fine if you just inline this

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java [hunk 3]
```diff
@@ -311,11 +320,23 @@ public MicrosoftStsTokenRequest createTokenRequest(@NonNull final MicrosoftStsAu
                 "Creating TokenRequest..."
         );
 
-        if (mConfig.getMultipleCloudsSupported() || request.getMultipleCloudAware()) {
-            Logger.verbose(TAG, "get cloud specific authority based on authorization response.");
-            setTokenEndpoint(getCloudSpecificTenantEndpoint(response));
+        OpenIdProviderConfigurationClient configurationClient = new OpenIdProviderConfigurationClient(request, response, ENDPOINT_VERSION);
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: nit `final`

File: common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/OpenIdProviderConfigurationClient.java [hunk 4]
```diff
@@ -54,16 +56,30 @@
...
     public OpenIdProviderConfigurationClient(@NonNull final String issuer) {
-        mIssuer = sanitize(issuer);
+        mIssuer = Uri.parse(sanitize(issuer)).toString();
+    }
+
+    public OpenIdProviderConfigurationClient(@NonNull final String authority, @NonNull final String path) {
+        this(authority, path, NA);
+    }
+
+    public OpenIdProviderConfigurationClient(@NonNull final String authority, @NonNull final String path, @NonNull final String endpointVersion) {
```
[the remark this answers is not in the document]
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/OpenIdProviderConfigurationClient.java]: Addressed

File: common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/OpenIdProviderConfigurationClient.java (hunk 2 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/OpenIdProviderConfigurationClient.java]: Addressed

File: common/src/main/java/com/microsoft/identity/common/internal/cache/MicrosoftStsAccountCredentialAdapter.java [hunk 5]
```diff
@@ -81,11 +79,7 @@ public AccessTokenRecord createAccessToken(
             accessToken.setHomeAccountId(SchemaUtil.getHomeAccountId(clientInfo));
             accessToken.setRealm(getRealm(strategy, response));
 
-            if (!StringUtil.isEmpty(response.getAuthority())) {
-                accessToken.setEnvironment(strategy.getIssuerCacheIdentifierFromAuthority(new URL(response.getAuthority())));
-            } else {
-                accessToken.setEnvironment(strategy.getIssuerCacheIdentifier(request));
-            }
+            accessToken.setEnvironment(strategy.getIssuerCacheIdentifierFromTokenEndpoint());
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/cache/MicrosoftStsAccountCredentialAdapter.java]: 💪

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java [hunk 6]
```diff
@@ -24,18 +24,48 @@
...
+        }
+        return getEndpoint(getAuthorityUrl(), FALLBACK_TOKEN_ENDPOINT_SUFFIX);
+    }
+
+
+    private URL getEndpoint(String endpoint) {
+        try {
+            return new URL(endpoint);
+        } catch (Exception e) {
+            e.printStackTrace();
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Let's log two errors here:
- 1 reporting the error using `Logger.error`
- 2 reporting the stacktrace + failing uri with `Logger.errorPII` (since this may contain OII)

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java [hunk 7]
```diff
@@ -24,18 +24,48 @@
...
-        return getEndpoint(getAuthorityUrl(), "/oAuth2/v2.0/token");
+        final OpenIdProviderConfiguration openIdConfig = getOpenIdWellKnownConfigForAuthority();
+        if (openIdConfig != null && openIdConfig.getTokenEndpoint() != null) {
+            return getEndpoint(openIdConfig.getTokenEndpoint());
+        }
+        return getEndpoint(getAuthorityUrl(), FALLBACK_TOKEN_ENDPOINT_SUFFIX);
+    }
+
+
+    private URL getEndpoint(String endpoint) {
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Let's also declare this return type `@Nullable`

Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: And param `@NonNull final`

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java [hunk 8]
```diff
@@ -24,18 +24,48 @@
...
+    private static final String TAG = MicrosoftStsOAuth2Configuration.class.getSimpleName();
+
+    private static final String ENDPOINT_VERSION = "v2.0";
+    private static final String FALLBACK_ENDPOINT_SUFFIX = "/oAuth2/v2.0";
+    private static final String FALLBACK_AUTHORIZE_ENDPOINT_SUFFIX = FALLBACK_ENDPOINT_SUFFIX + "/authorize";
+    private static final String FALLBACK_TOKEN_ENDPOINT_SUFFIX = FALLBACK_ENDPOINT_SUFFIX + "/token";
+
     public URL getAuthorizationEndpoint() {
-        return getEndpoint(getAuthorityUrl(), "/oAuth2/v2.0/authorize");
+        final OpenIdProviderConfiguration openIdConfig = getOpenIdWellKnownConfigForAuthority();
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Do we need to be mindful of what thread we're on when we call this method? If yes, can we javadoc?

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java [hunk 9]
```diff
@@ -53,4 +83,29 @@ private URL getEndpoint(URL root, String endpoint) {
 
     }
 
+    private OpenIdProviderConfiguration getOpenIdWellKnownConfigForAuthority() {
+        final URL authority = getAuthorityUrl();
+        return getOpenIdWellKnownConfig(authority.getHost(), authority.getPath());
+    }
+
+    OpenIdProviderConfiguration getOpenIdWellKnownConfig(final String host, final String audience) {
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: This looks like something that can't be call from the main thread -- if true, we should probably javadoc

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java [hunk 10]
```diff
@@ -53,4 +83,29 @@ private URL getEndpoint(URL root, String endpoint) {
 
     }
 
+    private OpenIdProviderConfiguration getOpenIdWellKnownConfigForAuthority() {
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Suggest we declare the return type `@Nullable` and javadoc that this method can return `null` if errors are encountered

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java (hunk 9 above)
Comment (iambmelt) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Let's also annotate the params as `@Nullable` or `@NonNull` as appropriate

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java (hunk 10 above)
Comment (iambmelt) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: and for completeness, that callers should check the result before using it

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java [hunk 11]
```diff
@@ -155,6 +160,27 @@ public String getIssuerCacheIdentifierFromAuthority(final URL authority) {
...
 
+    public String getIssuerCacheIdentifierFromTokenEndpoint() {
+        final String methodName = ":getIssuerCacheIdentifierFromTokenEndpoint";
+        URL authority = null;
+        String cacheIdentifier = null;
+
+        try {
+            authority = new URL(mTokenEndpoint);
+        } catch (MalformedURLException e) {
+            Logger.verbose(
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: Suggest we crank this up higher than `verbose`.... `warning` or `error` feels appropriate

**Comment by shahzaibj** [comment]
@iambmelt Yeah the pmd failed. Just pushed a fix for that. Also, I believe some end-to-end tests will also be broken and will need refactoring within MSAL. I'll create a PR to fix those prior to merging this.

**Comment by iambmelt** [comment]
> @iambmelt Yeah the pmd failed. Just pushed a fix for that. Also, I believe some end-to-end tests will also be broken and will need refactoring within MSAL. I'll create a PR to fix those prior to merging this.

Sounds great, thanks @shahzaibj

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java (hunk 6 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Addressed

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java (hunk 7 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Addressed

Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Addressed

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java (hunk 8 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Addressed. Yes, this is synchronous so it should not be called from the main thread. I've added the javadoc.

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java (hunk 9 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Addressed. Yes, this is synchronous so it should not be called from the main thread. I've added the javadoc.

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java (hunk 10 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Addressed

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java (hunk 11 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: Addressed

File: common/src/main/java/com/microsoft/identity/common/internal/request/AcquireTokenSilentOperationParameters.java [hunk 12]
```diff
@@ -61,8 +63,32 @@ public void validate() throws ArgumentException {
...
+                performCloudDiscovery();
+            }
+            final AzureActiveDirectoryCloud cloud = AzureActiveDirectory.getAzureActiveDirectoryCloud(mAccount.getEnvironment());
+            return cloud != null && cloud.getPreferredNetworkHostName().equals(getAuthority().getAuthorityURL().getAuthority());
+        } catch (IOException e) {
+            Logger.error(
+                    TAG + methodName,
+                    "Unable to perform cloud discovery",
+                    e);
+            return false;
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/request/AcquireTokenSilentOperationParameters.java]: What happens if this fails and we return false? Does the caller currently handle this in a reasonable way?

Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/request/AcquireTokenSilentOperationParameters.java]: We are just throw an ArgumentException in the case.
Since we are not sure if account matches the authority (as we don't have cloud information), we just say that the account does not match the authority and throw the exception.

Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/request/AcquireTokenSilentOperationParameters.java]: This is where this is called:

`    @Override
    public void validate() throws ArgumentException {
        super.validate();

        if (mAccount == null) {
            Logger.warn(TAG, "The account set on silent operation parameters is NULL.");
        } else if (!authorityMatchesAccountEnvironment()) {
            throw new ArgumentException(
                    ArgumentException.ACQUIRE_TOKEN_SILENT_OPERATION_NAME,
                    ArgumentException.AUTHORITY_ARGUMENT_NAME,
                    "Authority passed to silent parameters does not match with the cloud associated to the account."
            );
        }
    }`

File: common/src/main/java/com/microsoft/identity/common/internal/request/AcquireTokenSilentOperationParameters.java [hunk 13]
```diff
@@ -61,8 +63,32 @@ public void validate() throws ArgumentException {
...
+        }
+    }
+
+    private static void performCloudDiscovery() throws IOException {
+        final Object sLock = new Object();
```
Comment (iambmelt) [inline common/src/main/java/com/microsoft/identity/common/internal/request/AcquireTokenSilentOperationParameters.java]: I don't think this offering any protection as an instance variable....

Comment (iambmelt) [reply common/src/main/java/com/microsoft/identity/common/internal/request/AcquireTokenSilentOperationParameters.java]: each call would construct a new instance of the lock so it would always be free

Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/request/AcquireTokenSilentOperationParameters.java]: Addressed

**Comment by shahzaibj** [comment]
Thanks @iambmelt for review!

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java [hunk 14]
```diff
@@ -488,7 +497,7 @@ protected TokenResult getTokenResultFromHttpResponse(@NonNull final HttpResponse
         return result;
     }
 
-    private String getCloudSpecificTenantEndpoint(
+    private String buildCloudSpecificTokenEndpoint(
             @NonNull final MicrosoftStsAuthorizationResponse response) {
         if (!StringUtil.isEmpty(response.getCloudGraphHostName())) {
```
Comment (shahzaibj) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: @iambmelt I believe this should have been `if (!StringUtil.isEmpty(response.getCloudInstanceHostName()))`? as that is the one we use below. I'm going to make the change but wanted to double check if this was on purpose?

Comment (iambmelt) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: Looking....

Comment (iambmelt) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: This change was actually introduced in:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/commit/371212f51df69f7ad4bfafc3980b37c50ed2067b

It appears to be a typo

Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java]: Thanks, I'll make the change in this PR.

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectory/AzureActiveDirectory.java [hunk 15]
```diff
@@ -110,6 +110,14 @@ public static AzureActiveDirectoryCloud getAzureActiveDirectoryCloud(final URL a
         return sAadClouds.get(authorityUrl.getHost().toLowerCase(Locale.US));
     }
 
+    /**
+     * @param preferredCacheHostName String
+     * @return AzureActiveDirectoryCloud
+     */
+    public static AzureActiveDirectoryCloud getAzureActiveDirectoryCloud(final String preferredCacheHostName) {
```
Comment (kreedula) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectory/AzureActiveDirectory.java]: nit : rename `getAzureActiveDirectoryCloudFromHostName` to distinguish from the method above

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java [hunk 16]
```diff
@@ -24,18 +24,73 @@
...
-        return getEndpoint(getAuthorityUrl(), "/oAuth2/v2.0/token");
+        final OpenIdProviderConfiguration openIdConfig = getOpenIdWellKnownConfigForAuthority();
+        if (openIdConfig != null && openIdConfig.getTokenEndpoint() != null) {
+            return getEndpoint(openIdConfig.getTokenEndpoint());
+        }
+        return getEndpoint(getAuthorityUrl(), FALLBACK_TOKEN_ENDPOINT_SUFFIX);
+    }
+
+    @Nullable
+    private URL getEndpoint(@NonNull final String endpoint) {
```
Comment (kreedula) [inline common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: nit : rename method for clarity, also there is a method with a same name (from before) in this class , which lacks clarity too, these can get confusing

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectory/AzureActiveDirectory.java (hunk 15 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/azureactivedirectory/AzureActiveDirectory.java]: Addressed

File: common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java (hunk 16 above)
Comment (shahzaibj) [reply common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Configuration.java]: Addressed
